# Generated by Django 4.1.7 on 2023-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enter_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinders', models.TextField()),
                ('displacement', models.TextField()),
                ('horsepower', models.TextField()),
                ('weight', models.TextField()),
                ('acceleration', models.TextField()),
                ('model', models.TextField()),
                ('origin', models.TextField()),
            ],
        ),
    ]
