# Generated by Django 4.1.7 on 2023-03-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enter_details',
            new_name='enter_detail',
        ),
    ]
