# Generated by Django 4.1.7 on 2023-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_enter_detail_acceleration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_detail',
            name='cylinders',
            field=models.TextField(),
        ),
    ]
