# Generated by Django 4.1.7 on 2023-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_enter_detail_cylinders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_detail',
            name='cylinders',
            field=models.IntegerField(),
        ),
    ]
